export const API_KEY_ENV = "PUBLIC_FIREBASE_API_KEY";
export const AUTH_DOMAIN_ENV = "PUBLIC_FIREBASE_AUTH_DOMAIN";
export const PROJECT_ID_ENV = "PUBLIC_FIREBASE_PROJECT_ID";
export const APP_ID_ENV = "PUBLIC_FIREBASE_APP_ID";
